# Generated by Django 4.1 on 2022-08-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='question',
            new_name='keyword',
        ),
    ]
